server:
  port: ${PORT:8080}

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  data:
    mongodb:
#      host: localhost
#      port: 27017
      uri: ${MONGODB}
      database: BugBusters
      auto-index-creation: true